# Generated by Django 4.2.2 on 2023-06-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='starters',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('opinion', models.TextField(max_length=400, verbose_name='Содержание отзыва')),
                ('twitter', models.URLField(max_length=300, unique=True, verbose_name='twitter')),
                ('facebook', models.URLField(max_length=300, unique=True, verbose_name='facebook')),
                ('instagram', models.URLField(max_length=300, unique=True, verbose_name='instagram')),
                ('linkedin', models.URLField(max_length=300, unique=True, verbose_name='linkedin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.role', verbose_name='Роль павара')),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
