# Generated by Django 4.2.2 on 2023-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_role_alter_breakfast_price_alter_dinner_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Изображение'),
        ),
    ]
