# Generated by Django 4.2.2 on 2023-06-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chefs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название события'),
        ),
    ]
